- name: Add Nginx repository key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: Add Nginx repository
  apt_repository:
    repo: "deb http://nginx.org/packages/ubuntu/ jammy nginx"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes
  register: apt_update_result


- name: Install Nginx
  apt:
    name: nginx
    state: latest
