---
- name: Clone Git repository and run playbook
  hosts: localhost
  tasks:
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: /tmp/ansible/
        state: directory

    - name: Clone Git repository
      git:
        repo: git@github.com:xDeBian/ansible.git
        dest: /tmp/ansible/
        clone: yes
        update: yes

    - name: Run playbook
      ansible.builtin.command: ansible-playbook /tmp/ansible/site.yml
