---
- hosts: all
  become: yes
  roles:
    - node_exporter
    - nginx

- hosts: prometheus
  become: yes
  roles:
    - prometheus
    - alertmanager

- hosts: grafana
  become: yes
  roles:
    - grafana
