---
- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: Extract Node Exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp/"
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Move Node Exporter binary
  command: mv /tmp/node_exporter /usr/local/bin/

- name: Create Node Exporter user
  user:
    name: node_exporter
    shell: /bin/false
    system: yes

- name: Create Node Exporter systemd service
  copy:
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'

- name: Start and enable Node Exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes
