groups:
- name: Set Time Series Table
  rules:
  - alert: HighErrorRate
    expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "High request latency"
      description: "The request latency is over 0.5 seconds for more than 10 minutes."
